DROP TABLE IF EXISTS TBL_DOGS;

CREATE TABLE TBL_DOGS (
  id INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  age INT NOT NULL
);

DROP TABLE IF EXISTS TBL_CATS;

CREATE TABLE TBL_CATS (
  id INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  age INT NOT NULL
);

DROP TABLE IF EXISTS TBL_EMPLOYEE;

CREATE TABLE TBL_EMPLOYEE (
    id INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
    firstName VARCHAR(250) NOT NULL,
    lastName VARCHAR(250) NOT NULL,
    gender VARCHAR(50) NOT NULL,
    created_data VARCHAR(100) NOT NULL
);